services:
  location-service:
    build:
      context: Services.Location
      dockerfile: Dockerfile
    container_name: locationservice
    environment:
      - ConnectionString=Server=host.docker.internal,1433;Database=DealershipLocationService;User Id=dealership;Password=5sQTDF8GBaHrxFZ;TrustServerCertificate=True
    depends_on:
      - api-gateway
    networks:
      - app-network
      

  api-gateway:
    build:
      context: Api.Gateway
      dockerfile: Dockerfile
    container_name: apigateway
    ports:
      - "7100:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
